### ISSUE TITLE
Make sidebar open by default

### ISSUE THREAD

**Issue by kirka121** [kirka121/transop#5]
iirc its set up so it remembers the option since last reload (localstorage) and keeps that
but lets set the default to open

**Comment by atiqueakhtar** [comment]
Hi, @kirka121 I would like you to add a PR to resolve this issue. Can you please assign it to me?

**Comment by anoosh96** [comment]
Hey @kirka121, kindly review this [PR](https://github.com/kirka121/transop/pull/12)

**Comment by kirka121** [comment]
reviewed, merged. Thank you sir. @anoosh96
